export const config = {
  hlintPath: {
    type: 'string',
    default: 'hlint',
    description:
      'Full path to `hlint` binary, e.g. `C:\\Users\\myuser\\bin\\hlint.exe`, or' +
      '`/usr/local/bin/hlint`. You only need to change this if the directory where' +
      'your `hlint` binary is located is not on your system PATH.',
    order: 99,
  },
  checkAllFilesInProject: {
    type: 'boolean',
    default: false,
    description:
      'Try to check all *.hs files in current Atom project. ' +
      'Use with care, this may cause intermittent freezes on large code bases. ' +
      'When disabled, only runs hlint on the last saved file.',
    order: 0,
  },
  checkOnChange: {
    type: 'boolean',
    default: false,
    description:
      'Re-check current file on each change. ' +
      'Can be extremely distracting.',
    order: 10,
  },
  ignoreGlobs: {
    type: 'array',
    items: {
      type: 'string',
      minimum: 1.5,
      maximum: 11.5,
    },
    default: [
      '.cabal-sandbox/**',
      'dist/**',
      'dist-newstyle/**',
      '.stack-work/**',
    ],
    description: 'File globs to ignore; comma-separated',
    order: 20,
  },
}

// generated by typed-config.js
declare module 'atom' {
  interface ConfigValues {
    'ide-haskell-hlint.hlintPath': string
    'ide-haskell-hlint.checkAllFilesInProject': boolean
    'ide-haskell-hlint.checkOnChange': boolean
    'ide-haskell-hlint.ignoreGlobs': string[]
    'ide-haskell-hlint': {
      hlintPath: string
      checkAllFilesInProject: boolean
      checkOnChange: boolean
      ignoreGlobs: string[]
    }
  }
}
